### ISSUE TITLE
Terraform apply fails with conversion error

### ISSUE THREAD

**Issue by clincha** [clincha-org/clincha#119]
```text
│ Error: Plugin did not respond
│ 
│   with module.bri-master-1.proxmox_vm_qemu.rocky8,
│   on modules/rocky8/rocky8.tf line 1, in resource "proxmox_vm_qemu" "rocky8":
│    1: resource "proxmox_vm_qemu" "rocky8" {
│ 
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may
│ contain more details.
╵
Stack trace from the terraform-provider-proxmox_v2.9.14 plugin:
panic: interface conversion: interface {} is string, not float64
goroutine 69 [running]:
github.com/Telmate/proxmox-api-go/proxmox.NewConfigQemuFromApi(0xc0003f63c0, 0x0?)
	github.com/Telmate/proxmox-api-go@v0.0.0-202[303](https://github.com/clincha-org/clincha/actions/runs/7494644861/job/20403014370#step:5:304)19185744-e7cde7198cdf/proxmox/config_qemu.go:584 +0x4605
github.com/Telmate/terraform-provider-proxmox/proxmox.prepareDiskSize(0x0?, 0xc0003f08c0?, 0xc?, 0xc0005aa090?)
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1737 +0xeb
github.com/Telmate/terraform-provider-proxmox/proxmox.resourceVmQemuCreate(0xc0000dec00, {0xb66f60?, 0xc0004a4640})
	github.com/Telmate/terraform-provider-proxmox/proxmox/resource_vm_qemu.go:1059 +0x1cb2
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xdd7840?, {0xdd7840?, 0xc0003d5800?}, 0xd?, {0xb66f60?, 0xc0004a4640?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:695 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000e6ee0, {0xdd7840, 0xc0003d5800}, 0xc0003fa820, 0xc0000de200, {0xb66f60, 0xc0004a4640})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/resource.go:837 +0xa85
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc00036ff08, {0xdd7840?, 0xc0003d56b0?}, 0xc00008a4b0)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.25.0/helper/schema/grpc_provider.go:1021 +0xe8d
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00021a460, {0xdd7840?, 0xc0004af800?}, 0xc0000e07e0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:818 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xc6bc20?, 0xc00021a460}, {0xdd7840, 0xc0004af800}, 0xc0000e0770, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:385 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002061e0, {0xddb420, 0xc000482340}, 0xc0002446c0, 0xc00037d890, 0x128f7a0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1336 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0002061e0, {0xddb420, 0xc000482340}, 0xc0002446c0, 0x0)
	google.golang.org/grpc@v1.53.0/server.go:1704 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.53.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.53.0/server.go:963 +0x28a
Error: The terraform-provider-proxmox_v2.9.14 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
Error: Process completed with exit code 1.
```

**Comment by clincha** [comment]
https://github.com/Telmate/terraform-provider-proxmox/issues/898
